apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Nginx-API
  description: The Nginx API
  tags:
    - nginx
    - rest
  annotations:
    # The annotation is deprecated, we use placeholders (see below) instead, remove it later.
    backstage.io/definition-at-location: 'url:https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/spotify.com/v1/swagger.yaml'
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: https://github.com/ducthanh1809/nginx-dapi/blob/main/openapi.yaml
